using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Photon.Pun;
using Photon.Realtime;

public class PhotonManager : MonoBehaviourPunCallbacks
{
    private readonly string version = "1.0f";
    private string userId = "KSH";
    private GameObject localPlayer;

    private void Awake()
    {
        PhotonNetwork.AutomaticallySyncScene = true;
        PhotonNetwork.GameVersion = version;
        PhotonNetwork.NickName = userId;

        Debug.Log(PhotonNetwork.SendRate); // 포톤서버와 통신 횟수 (30)
        PhotonNetwork.ConnectUsingSettings(); // 서버 접속
    }

    public override void OnConnectedToMaster()
    {
        Debug.Log("Connected To Master!");
        PhotonNetwork.JoinLobby();
    }

    public override void OnJoinedLobby()
    {
        base.OnJoinedLobby();
        Debug.Log($"Connected To Lobby = {PhotonNetwork.InLobby}");
        PhotonNetwork.JoinRandomRoom();
    }

    public override void OnJoinRandomFailed(short returnCode, string message)
    {
        Debug.Log($"Join Failed {returnCode} : {message}");

        RoomOptions ro = new RoomOptions();
        ro.MaxPlayers = 20;
        ro.IsOpen = true;
        ro.IsVisible = true;

        PhotonNetwork.CreateRoom("My Room", ro);
    }

    public override void OnCreatedRoom()
    {
        Debug.Log("Created Room!");
        Debug.Log($"Room Name = {PhotonNetwork.CurrentRoom.Name}");
    }

    public override void OnJoinedRoom()
    {
        Debug.Log($"In Room = {PhotonNetwork.InRoom}");
        Debug.Log($"Player Count = {PhotonNetwork.CurrentRoom.PlayerCount}");

        foreach (var player in PhotonNetwork.CurrentRoom.Players)
        {
            Debug.Log($"{player.Value.NickName}, {player.Value.ActorNumber}");
        }

        Transform[] points = GameObject.Find("CreatePlayerGroup").GetComponentsInChildren<Transform>();
        int idx = Random.Range(1, points.Length);

        // 로컬 플레이어 생성 및 PhotonView 연결
        localPlayer = PhotonNetwork.Instantiate("Player", points[idx].position, points[idx].rotation, 0);

        // 카메라 생성 및 로컬 플레이어에 할당
        GameObject camera = Instantiate(Resources.Load<GameObject>("Camera"));  // Camera Prefab을 Resources에서 로드하여 생성
        camera.GetComponent<CameraFollow>().SetTarget(localPlayer.transform);
    }

    private void Update()
    {
    }
}
